:standard-fail-text: Verify that you followed all the steps. If you continue to have issues, contact a workshop assistant.
:namespace: {user-username}
:idp: GitHub
:ocm-url: https://cloud.redhat.com
:osd-name: OpenShift Dedicated
:osd-acronym: OSD
:rhoam-name: Red Hat OpenShift API Management
:rhoam-acronym: RHOAM
:3scale-name: 3scale API Management
:sso-name: Single Sign-On
:3scale-toolbox: 3Scale toolbox
:sso-name-short: Red Hat SSO



= Red Hat OpenShift API Management Introduction
:page-layout: home
:!sectids:

[.text-center.strong]
== Introduction

Welcome to the Red Hat OpenShift API Management workshop

Red Hat® OpenShift® API Management (RHOAM) is a hosted and managed API management service delivered as an add-on product to Red Hat OpenShift Dedicated, a fully managed service of enterprise Kubernetes platform Red Hat OpenShift. 

RHOAM  supports teams that want to take an API-first approach to building microservices-based applications so they can modernize existing systems, increase developer productivity, and deliver new applications faster. OpenShift API Management also includes Red Hat OpenShift Service Registry at no extra cost.

In this workshop you will:

* Create and setup Red Hat OpenShift API Management 
* Use 3scale Service Discovery to import APIs, create applications plans and make calls to APIs using API Key security
* Use and observe the API Management Dashboard (Grafana) for rate limiting status. 
* Secure an API managed with 3scale API Management using OpenID Connect (OIDC), using the Red Hat Single Sign-On instance of RHOAM as identity provider.
* Use 3scale toolbox to help administrators operate their APIs, and help automate the delivery of these APIs through Continuous Delivery pipelines.
* Setup monitoring tools for RHOAM. 

This workshop uses the link:https://developers.redhat.com/developer-sandbox[Developer Sandbox for Red Hat OpenShift], which provides you with a private OpenShift environment in a shared, multi-tenant OpenShift cluster that is pre-configured with a set of developer tools. This also means you won't have to install anything on your workstation in order to run this workshop.

[.tiles.browse]
== Browse modules

[.tile]

include::../nav.adoc[]


